params:
  genomes: "genomes.tsv"

predict:
  do: False
  mode: "single"
  format: "gff"

checkm:
  do: False
  table: "checkm_table.tsv"
  batch_num: 1000

dereplicate:
  cdhit:
    rename: True
    threads: 32
    sequence_identity_threshold: 0.95
    alignment_coverage_for_shorter_sequence: 0.9
    word_length: 8
    use_global_sequence_identity: 0
    memory_limit: 0
    cluster_description_length: 0
    default_algorithm: 0
    both_alignment: 1

  linclust:

  drep:

  galah:
    min_completeness: ""
    max_contamination: ""
    ani: 99
    min_aligned_fraction: 50
    fragment_length: 3000
    quality_formula: "Parks2020_reduced"
    # formula                        description
    # Parks2020_reduced              (default) completeness-5*contamination-5*num_contigs/100-5*num_ambiguous_bases/100000
    # completeness-4contamination    completeness-4*contamination
    # completeness-5contamination    completeness-5*contamination
    # dRep                           completeness-5*contamination+contamination*(strain_heterogeneity/100)+0.5*log10(N50)
    precluster_ani: 95
    precluster_method: "dashing"
    # 'dashing' for HyperLogLog
    # 'finch' for finch MinHash. [default: dashing]

output:
  checkm: "results/checkm.out"
  drep: "results/drep.out"
  galah: "results/galah.out"
