#!/usr/bin/env snakemake

import os
import sys

import metapi
import snakemake
import pandas as pd


def parse_genomes(genomes_tsv):
    df = pd.read_csv(genomes_tsv, sep='\t').set_index("id")


SAMPLES = parse_genomes(config["genomes"])


include: "prepare.smk"
include: "drep.smk"
include: "galah.smk"


rule all:
    rules.dereplicate_drep_all.input,
    rules.dereplicate_galah_all.input
